# Generated by Django 4.0 on 2021-12-23 06:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='top',
            options={},
        ),
        migrations.AlterField(
            model_name='top',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='tops'),
        ),
    ]
